# Generated by Django 4.1.4 on 2022-12-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0005_alter_event_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='img',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='img',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
